name: PHP Tests

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v1

    - name: setup PHP
      uses: shivammathur/setup-php@master
      with: 
        php-version: ${{ matrix.php-versions }}
        extension: intl, json, mbstring, xdebug, xml
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: phpunit.xml.dist && composer test

